=== SacredScriptureFoundation/sacredscripture/xml/src/main/xsd/nls-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2013, 2014 Sacred Scripture Foundation.
  "All scripture is given by inspiration of God, and is profitable for 
  doctrine, for reproof, for correction, for instruction in righteousness:
  That the man of God may be perfect, throughly furnished unto all good 
  works." (2 Tim 3:16-17)
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<schema 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://www.sacredscripturefoundation.org/schema/nls" 
  xmlns:nls="http://www.sacredscripturefoundation.org/schema/nls"
  xmlns:bible="http://www.sacredscripturefoundation.org/schema/bible"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified" 
  version="1.0">

  <import namespace="http://www.sacredscripturefoundation.org/schema/bible" schemaLocation="http://www.sacredscripturefoundation.org/schema/bible-1.0.xsd" />

  <element name="nls">
    <complexType>
      <sequence>
        <element name="group" type="nls:GroupType" maxOccurs="unbounded">
          <unique name="UniqueGroupLocalization">
            <selector xpath="nls:localization" />
            <field xpath="@lang" />
          </unique>
        </element>
        <element name="book" type="nls:BookType" minOccurs="73" maxOccurs="73">
          <unique name="UniqueBookLocalization">
            <selector xpath="nls:localization" />
            <field xpath="@lang" />
          </unique>
        </element>
      </sequence>
    </complexType>
  </element>

  <complexType name="BookType">
    <sequence>
      <element name="localization" type="nls:BookTypeLocalization" maxOccurs="unbounded" />
    </sequence>
    <attribute name="code" type="bible:BookCodeType" use="required" />    
  </complexType>

  <complexType name="BookTypeLocalization">
    <attribute name="lang" type="language" use="required" />
    <attribute name="name" type="string" use="required" />
    <attribute name="title" type="string" use="required" />
    <attribute name="abbreviations" type="string" use="required" />
  </complexType>

  <complexType name="GroupType">
    <sequence>
      <element name="localization" type="nls:GroupLocalizationType" maxOccurs="unbounded" />
    </sequence>
    <attribute name="code" type="string" use="required" />
  </complexType>
  
  <complexType name="GroupLocalizationType">
    <attribute name="lang" type="language" use="required" />
    <attribute name="name" type="string" use="required" />
  </complexType>

</schema>

=== SacredScriptureFoundation/sacredscripture/src/xml/nls.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
  Copyright (c) 2013, 2014 Sacred Scripture Foundation.
  "All scripture is given by inspiration of God, and is profitable for 
  doctrine, for reproof, for correction, for instruction in righteousness:
  That the man of God may be perfect, throughly furnished unto all good 
  works." (2 Tim 3:16-17)
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<nls 
  xmlns="http://www.sacredscripturefoundation.org/schema/nls" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.sacredscripturefoundation.org/schema/nls http://www.sacredscripturefoundation.org/schema/nls-1.0.xsd">

  <!-- Book Groups -->

  <group code="cat">
    <localization lang="en" name="General Epistles" />
    <localization lang="es" name="Cartas Generales" />
    <localization lang="la" name="General Epistolis" />
    <localization lang="pl" name="Listy powszechne" />
  </group>

  <group code="gos">
    <localization lang="en" name="Gospels" />
    <localization lang="es" name="Evangelios" />
    <localization lang="la" name="Evangelia" />
    <localization lang="pl" name="Ewangelie" />
  </group>

  <group code="his">
    <localization lang="en" name="Historical Books" />
    <localization lang="es" name="Libros Históricos" />
    <localization lang="la" name="Historica" />
    <localization lang="pl" name="Księgi Historyczne" />
  </group>
  
  <group code="mos">
    <localization lang="en" name="Pentateuch" />
    <localization lang="es" name="Pentateuco" />
    <localization lang="la" name="Pentateuchus" />
    <localization lang="pl" name="Pięcioksiąg" />
  </group>

  <group code="ntt">
    <localization lang="en" name="New Testament" />
    <localization lang="es" name="Nuevo Testamento" />
    <localization lang="la" name="Novum Testamentum" />
    <localization lang="pl" name="Nowy Testament" />
  </group>
  
  <group code="ott">
    <localization lang="en" name="Old Testament" />
    <localization lang="es" name="Antiguo Testamento" />
    <localization lang="la" name="Vetus Testamentum" />
    <localization lang="pl" name="Stary Testament" />
  </group>
  
  <group code="pau">
    <localization lang="en" name="Pauline Epistles" />
    <localization lang="es" name="Cartas de San Pablo" />
    <localization lang="la" name="Epistulae sancti Paul" />
    <localization lang="pl" name="Listy Pawła" />
  </group>

  <group code="pma">
    <localization lang="en" name="Major Prophets" />
    <localization lang="es" name="Profetas Mayores" />
    <localization lang="la" name="Major Prophetae" />
    <localization lang="pl" name="Prorocy Więksi" />
  </group>

  <group code="pmi">
    <localization lang="en" name="Minor Prophets" />
    <localization lang="es" name="Profetas Mayores" />
    <localization lang="la" name="Major Prophetae" />
    <localization lang="pl" name="Prorocy Mniejsi" />
  </group>

  <group code="pro">
    <localization lang="en" name="The Prophets" />
    <localization lang="es" name="Los Profetas" />
    <localization lang="la" name="Prophetae" />
    <localization lang="pl" name="Prorocy" />
  </group>
  
  <group code="wis">
    <localization lang="en" name="Wisdom Books" />
    <localization lang="es" name="libros de Sabiduría" />
    <localization lang="la" name="Sapientia Libros" />
    <localization lang="pl" name="Księgi Mądrości" />
  </group>
  
  <!-- Books -->

  <book code="act">
    <localization lang="en" name="Acts" title="The Acts of the Apostles" abbreviations="Act,Ac" />
    <localization lang="es" name="Hechos" title="Hechos de los Apóstoles" abbreviations="Hech,Hch,He" />
    <localization lang="la" name="Actus Apostolorum" title="Actus Apostolorum" abbreviations="Ac" />
    <localization lang="pl" name="Dzieje Apostolskie" title="Księga Dziejów Apostolskich" abbreviations="Dz,TODO" />
  </book>

  <book code="amo">
    <localization lang="en" name="Amos" title="The Book of the Prophet Amos" abbreviations="Am" />
    <localization lang="es" name="Amós" title="Libro del profeta Amós" abbreviations="Am" />
    <localization lang="la" name="Amos" title="Prophetia Amos" abbreviations="Am" />
    <localization lang="pl" name="Amosa" title="Księgi proroka Amosa" abbreviations="TODO" />
  </book>

  <book code="bar">
    <localization lang="en" name="Baruch" title="The Book of the Prophet Baruch" abbreviations="Bar,Ba" />
    <localization lang="es" name="Baruc" title="Libro del profeta Baruc" abbreviations="Bar,Ba" />
    <localization lang="la" name="Baruch" title="Prophetia Baruch" abbreviations="Bar" />
    <localization lang="pl" name="Barucha" title="Księgi proroka Barucha" abbreviations="Bar,Ba" />
  </book>

  <book code="ch1">
    <localization lang="en" name="1 Chronicles" title="The First Book of Chronicles" abbreviations="1Chr,1Chron,1Ch" />
    <localization lang="es" name="1 Crónicas" title="Libro Primero de las Crónicas" abbreviations="1Cró,1Cr" />
    <localization lang="la" name="Paralipomenon I" title="Liber Primus Paralipomenon" abbreviations="1Par" />
    <localization lang="pl" name="1 Kronik" title="Pierwsza Księga Kronik" abbreviations="2Kron,2Krn,TODO" />
  </book>

  <book code="ch2">
    <localization lang="en" name="2 Chronicles" title="The Second Book of Chronicles" abbreviations="2Chr,2Chron,2Ch" />
    <localization lang="es" name="2 Crónicas" title="Libro Segundo de las Crónicas" abbreviations="2Cró,2Cr" />
    <localization lang="la" name="Paralipomenon II" title="Liber Secundus Paralipomenon" abbreviations="2Par" />
    <localization lang="pl" name="2 Kronik" title="Druga Księga Kronik" abbreviations="2Kron,2Krn,TODO" />
  </book>

  <book code="co1">
    <localization lang="en" name="1 Corinthians" title="The First Letter of St. Paul to the Corinthians" abbreviations="1Cor,1Co" />
    <localization lang="es" name="1 Corintios" title="Primera Carta de San Pablo a los Corintios" abbreviations="1Co" />
    <localization lang="la" name="ad Corinthios I" title="Epistola B. Pauli Apostoli ad Corinthios Prima" abbreviations="1Cor" />
    <localization lang="pl" name="1 Koryntian" title="Pierwszy List Pawła do Koryntian" abbreviations="1Kor,TODO" />
  </book>

  <book code="co2">
    <localization lang="en" name="2 Corinthians" title="The Second Letter of St. Paul to the Corinthians" abbreviations="2Cor,2Co" />
    <localization lang="es" name="2 Corintios" title="Segunda Carta de San Pablo a los Corintios" abbreviations="2Co" />
    <localization lang="la" name="ad Corinthios II" title="Epistola B. Pauli Apostoli ad Corinthios Secunda" abbreviations="2Cor" />
    <localization lang="pl" name="2 Koryntian" title="Drugi List św Pawła do Koryntian" abbreviations="2Kor,TODO" />
  </book>

  <book code="col">
    <localization lang="en" name="Colossians" title="The Letter of St. Paul to the Colossians" abbreviations="Col,Co" />
    <localization lang="es" name="Colosenses" title="Carta de San Pablo a los Colosenses" abbreviations="Col" />
    <localization lang="la" name="ad Colossenses" title="Epistola B. Pauli Apostoli ad Colossenses" abbreviations="Col" />
    <localization lang="pl" name="Kolosan" title="List Pawła do Kolosan" abbreviations="Kol,TODO" />
  </book>

  <book code="dan">
    <localization lang="en" name="Daniel" title="The Book of the Prophet Daniel" abbreviations="Dan,Dn,Da" />
    <localization lang="es" name="Daniel" title="Libro del profeta Daniel" abbreviations="Dan,Dn" />
    <localization lang="la" name="Daniel" title="Prophetia Danielis" abbreviations="Dan,Dn" />
    <localization lang="pl" name="Daniela" title="Księgi proroka Daniela" abbreviations="TODO" />
  </book>

  <book code="deu">
    <localization lang="en" name="Deuteronomy" title="The Fifth Book of Moses commonly called Deuteronomy" abbreviations="Deut,Dt,De,Du" />
    <localization lang="es" name="Deuteronomio" title="Libro Quinto de Moses llamó Deuteronomio" abbreviations="Deut,Dt" />
    <localization lang="la" name="Deuteronomium" title="Liber Quinto Mosis dicitur Deuteronomii" abbreviations="Deut,Dt" />
    <localization lang="pl" name="Powtórzonego Prawa" title="Piąta Księga Mojżesza nazywa Powtórzonego Prawa" abbreviations="Pwt,TODO" />
  </book>

  <book code="ecc">
    <localization lang="en" name="Ecclesiastes" title="Ecclesiastes (or the Preacher)" abbreviations="Eccl,Ec,Eccles" />
    <localization lang="es" name="Eclesiastés" title="Eclesiastés (Qohélet)" abbreviations="Ecl,Ec" />
    <localization lang="la" name="Ecclesiastes" title="Liber Ecclesiastes" abbreviations="Ecl" />
    <localization lang="pl" name="Koheleta" title="Księga Koheleta" abbreviations="Koh,TODO" />
  </book>

  <book code="eph">
    <localization lang="en" name="Ephesians" title="The Letter of St. Paul to the Ephesians" abbreviations="Eph,Ep" />
    <localization lang="es" name="Efesios" title="Carta de San Pablo a los Efesios" abbreviations="Ef" />
    <localization lang="la" name="ad Ephesios" title="Epistola B. Pauli Apostoli ad Ephesios" abbreviations="Eph,Ep" />
    <localization lang="pl" name="Efezjan" title="List Pawła do Efezjan" abbreviations="Efez,Ef" />
  </book>

  <book code="est">
    <localization lang="en" name="Esther" title="The Book of Esther" abbreviations="Esth,Es,Est" />
